# Generated by Django 5.0.6 on 2024-06-29 18:22

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_newsarticle_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to=api.models.rename_file),
        ),
    ]
