
services:
  webserver-prod:
    image: ghcr.io/philippgoetz1995/playground-webserver:latest
    ports:
      - "80:80"
    networks:
      - webnet
    environment:
      - NODE_ENV=production

  backend-prod:
    image: ghcr.io/philippgoetz1995/playground-backend:latest
    ports:
      - "8000:8000"
    networks:
      - webnet
    env_file:
      - .env.prod
    environment:
      - NODE_ENV=production
      - DJANGO_SETTINGS_MODULE=backend.settings.production

networks:
  webnet: