services:
  frontend-stage:
    build:
      # With the context all paths need below will start from the directory where the compose file is in
      context: .
      dockerfile: ./frontend/Dockerfile-stage
      args:
        REACT_APP_API_URL: http://localhost:8000/
    ports:
      - "3000:3000"
    volumes:
      # Mount local src folder with container src folder
      - ./frontend/src:/app/src
    networks:
      - webnet
    environment:
      # This is needed so that mounted volume for react application is working
      - WATCHPACK_POLLING=true
      - NODE_ENV=development

  backend-stage:
    build:
      # With the context all paths need below will start from the directory where the compose file is in
      context: .
      dockerfile: ./backend/Dockerfile-stage
    ports:
      - "8000:8000"
    volumes:
      # Mount local src folder with container for development so that changes are reflected immediately
      - ./backend:/app
      - static_volume:/app/staticfiles
    networks:
      - webnet
    env_file:
      - .env.stage
    environment:
      - NODE_ENV=development
      - DJANGO_SETTINGS_MODULE=backend.settings.stage

  webserver-stage:
    build:
      # With the context all paths need below will start from the directory where the compose file is in
      context: .
      dockerfile: ./webserver/Dockerfile-stage
    ports:
      - "80:80"
    volumes:
      - ./webserver/nginx-stage.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - frontend-stage
      - backend-stage
    networks:
      - webnet

# With that network the following call is possible from nginx configuration http://frontend:3000;
networks:
  webnet:

volumes:
  static_volume:
