# This file is used to build the images for the production environment
# There is then a second file docker-compose-prod.yml which will run the containers as soon the container is on the server

services:
  backend-prod:
    # Create image with name ghcr.io/philippgoetz1995/playground-backend:latest => the push to github container registry (ghcr) will happen later
    image: ghcr.io/philippgoetz1995/playground-backend:latest
    build:
      # With the context all paths need below will start from the directory where the compose file is in
      context: .
      dockerfile: ./backend/Dockerfile-prod

  # The webserver is building the react app and serving it => therefore frontend is included
  webserver-prod:
    image: ghcr.io/philippgoetz1995/playground-webserver:latest
    build:
      # With the context all paths need below will start from the directory where the compose file is in
      context: .
      dockerfile: ./webserver/Dockerfile-prod

# With that network the following call is possible from nginx configuration http://frontend:3000;
networks:
  webnet:
