# Use an official Python runtime as a parent image
FROM python:3.11-alpine

# Accept dynamic values from CI
ARG VERSION
ARG BUILD_DATE

# OCI labels (these show in Docker Desktop + docker inspect)
LABEL org.opencontainers.image.title="playground-backend-prod" \
      org.opencontainers.image.mainteiner="Philipp Goetz" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.created="${BUILD_DATE}"

# Set the working directory
WORKDIR /app

# Install specific pip version to not run into issues with the pip version
RUN pip install --no-cache-dir pip==23.3.1

# Install sqlite
RUN apk add --no-cache sqlite

# Install dependencies
COPY backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY backend/. .

# Make the startup script executable
RUN chmod +x start-prod.sh

# Expose port 8000
EXPOSE 8000

# Use the startup script as the entrypoint
CMD ["./start-prod.sh"]