# Use an official Python runtime as a parent image
FROM python:3.11-alpine

# Set the working directory
WORKDIR /app

# Install specific pip version to not run into issues with the pip version
RUN pip install --no-cache-dir pip==23.3.1

# Install dependencies
COPY backend/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY backend/. .

# Expose port 8000
EXPOSE 8000

# Start gunicorn and bind the application to the correct port => "backend.wsgi" is the starting point for the application
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi:application"]