
# ----- First Section is only to build the production folder  of REACT ------

# Use an official Node.js image as the base image
FROM node:18-alpine AS build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY ../frontend/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code
COPY ../frontend/. .

# Build the React app for production
RUN npm run build

# ----- Second Section then to copy the build folder and start nginx webserver ------

# Use nginx:alpine as the base image
FROM nginx:alpine

# Copy the build files from the previous stage
COPY --from=build /app/build /usr/share/nginx/html

# Copy custom nginx config (optional)
COPY ../webserver/nginx-prod.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]