
# ----- First Section is only to build the production folder  of REACT ------

# Use an official Node.js image as the base image
FROM node:18-alpine AS build

# Accept dynamic values from CI
ARG VERSION
ARG BUILDDATE

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY ../frontend/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code
COPY ../frontend/. .

# Create version.json file during build
RUN echo '{' > public/version.json && \
    echo '  "version": "'${VERSION}'",' >> public/version.json && \
    echo '  "shortSha": "'${BUILDDATE}'",' >> public/version.json && \
    echo '  "builtAt": "'${BUILDDATE}'"' >> public/version.json && \
    echo '}' >> public/version.json && \
    cat public/version.json

# Build the React app for production
RUN npm run build

# ----- Second Section then to copy the build folder and start nginx webserver ------

# Use nginx:alpine as the base image
FROM nginx:alpine

# Accept dynamic values from CI
ARG VERSION
ARG BUILDDATE

# OCI labels (these show in Docker Desktop + docker inspect)
LABEL org.opencontainers.image.title="playground-webserver-prod" \
      org.opencontainers.image.mainteiner="Philipp Goetz" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.created="${BUILDDATE}"

# Copy the build files from the previous stage
COPY --from=build /app/build /usr/share/nginx/html

# Copy custom nginx config (optional)
COPY ../webserver/nginx-prod.conf /etc/nginx/nginx-prod.conf

# Expose port 80
EXPOSE 80

# Start Nginx
CMD ["nginx", "-c", "/etc/nginx/nginx-prod.conf", "-g", "daemon off;"]
