name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOSTNAME: ${{secrets.HOST_DNS}}
          USER_NAME: ${{secrets.USERNAME}}

        run: |
          echo "$PRIVATE_KEY" > github-connect.pem
          chmod 600 github-connect.pem

          ssh -o StrictHostKeyChecking=no -i github-connect.pem ec2-user@3.76.35.196

          cd hello

          git clone https://github.com/PhilippGoetz1995/playground.git
